export { parseGitLog, GIT_LOG_FORMAT, GIT_LOG_SEP, GIT_LOG_END } from './git-parser'
export type { ParsedCommit } from './git-parser'
export { fetchGitCommits, checkGitRepo, isTauri, getGitLogCommand } from './git-service'
export { ingestCommits } from './git-ingest'
export type { IngestProgress, ProgressCallback } from './git-ingest'
